name: Single Build Workflow

on:
    workflow_dispatch:
        inputs:
            service:
                description: "The service to build"
                required: true
                type: choice
                options:
                    - fixcore
                    - fixmetrics
                    - fixshell
                    - fixworker

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Build Docker Image
              run: |
                  docker build -f Dockerfile.${{ inputs.service }} -t ascintra-${{ inputs.service }}-${{ github.run_id }} .
